// src/components/markets/data/marketData.js

export const MARKET_INDICES = [
    { name: 'S&P 500',   change: '+0.84%', positive: true  },
    { name: 'NASDAQ',    change: '+1.21%', positive: true  },
    { name: 'Dow Jones', change: '-0.12%', positive: false },
    { name: 'NIFTY 50',  change: '+0.66%', positive: true  },
    { name: 'SENSEX',    change: '+0.58%', positive: true  },
    { name: 'Bitcoin',   change: '+2.10%', positive: true  },
    { name: 'Gold',      change: '+0.37%', positive: true  },
  ];
  
  export const STOCKS = [
    {
      id: 1,
      ticker: 'NVDA',
      name: 'NVIDIA Corporation',
      shortName: 'NVIDIA Corp.',
      initials: 'NV',
      sector: 'AI & Semiconductors',
      exchange: 'NASDAQ',
      market: 'US Market',
      price: 875.40,
      change: 4.28,
      changePositive: true,
      marketCap: '$2.1T',
      pe: '65.2x',
      peRaw: 65.2,
      revenueGrowth: '122%',
      revenueGrowthRaw: 122,
      grossMargin: '73.8%',
      operatingMargin: '54.1%',
      roe: '88.4%',
      marketStatus: 'open',
      accentColor: '#76b900',
      peers: [
        { ticker: 'NVDA', company: 'NVIDIA',  pe: '65.2x', revenueGrowth: '122%', isSelf: true  },
        { ticker: 'AMD',  company: 'AMD',     pe: '42.1x', revenueGrowth: '18%',  isSelf: false },
        { ticker: 'AVGO', company: 'Broadcom',pe: '31.5x', revenueGrowth: '21%',  isSelf: false },
      ],
      aiInsight: {
        standout: [
          'Exceptional revenue acceleration at 122% YoY driven by AI training demand',
          'Industry-leading gross margins of 73.8% rare for a hardware company',
          'Near-monopoly positioning in AI GPU market with H100 and H200 chips',
        ],
        watch: [
          'Valuation premium at 65x P/E is priced for perfection — any miss could be severe',
          'Data center demand sustainability beyond the initial AI infrastructure buildout',
          'Competitive pressure from AMD MI300X, Google TPU, and AWS Trainium',
        ],
        takeaway:
          'NVDA currently represents a high-growth, high-expectation investment profile with unusually strong profitability metrics for a semiconductor company.',
      },
      catalysts: [
        { date: 'Aug 2024', text: 'Q2 FY25 earnings beat consensus by 12%; EPS $0.68 vs $0.61 expected' },
        { date: 'Jul 2024', text: 'Data center revenue reached $26.3B quarterly — a new all-time record' },
        { date: 'Jun 2024', text: 'Blackwell GPU architecture announced with 2.5x performance leap over Hopper' },
        { date: 'May 2024', text: 'Management raised full-year revenue guidance by 15% at midpoint' },
      ],
    },
    {
      id: 2,
      ticker: 'AAPL',
      name: 'Apple Inc.',
      shortName: 'Apple Inc.',
      initials: 'AP',
      sector: 'Technology',
      exchange: 'NASDAQ',
      market: 'US Market',
      price: 227.52,
      change: 0.83,
      changePositive: true,
      marketCap: '$3.5T',
      pe: '32.1x',
      peRaw: 32.1,
      revenueGrowth: '8%',
      revenueGrowthRaw: 8,
      grossMargin: '46.2%',
      operatingMargin: '30.4%',
      roe: '147.9%',
      marketStatus: 'open',
      accentColor: '#555555',
      peers: [
        { ticker: 'AAPL', company: 'Apple',     pe: '32.1x', revenueGrowth: '8%',  isSelf: true  },
        { ticker: 'MSFT', company: 'Microsoft', pe: '35.2x', revenueGrowth: '16%', isSelf: false },
        { ticker: 'GOOG', company: 'Alphabet',  pe: '23.4x', revenueGrowth: '14%', isSelf: false },
      ],
      aiInsight: {
        standout: [
          'Unmatched ecosystem lock-in across 2B+ active devices globally',
          'Services segment growing at 14% YoY with 75%+ gross margins',
          'Extraordinary ROE of 147.9% driven by aggressive capital return programs',
        ],
        watch: [
          'iPhone unit growth plateauing in saturated premium smartphone markets',
          'Regulatory pressure on App Store commission structure in EU and US',
          'China revenue exposure at ~17% amid ongoing geopolitical tensions',
        ],
        takeaway:
          'Apple represents a mature cash-flow machine with services-driven margin expansion, trading at a premium justified primarily by ecosystem stickiness and capital return programs.',
      },
      catalysts: [
        { date: 'Aug 2024', text: 'Apple Intelligence AI features announced for iOS 18 across all product lines' },
        { date: 'Jul 2024', text: 'Services revenue hit $24.2B quarterly — growing 14% year-over-year' },
        { date: 'Jun 2024', text: 'WWDC 2024 showcased deep ChatGPT integration built directly into Siri' },
        { date: 'May 2024', text: '$110B share buyback announced — the largest in company history' },
      ],
    },
    {
      id: 3,
      ticker: 'MSFT',
      name: 'Microsoft Corporation',
      shortName: 'Microsoft Corp.',
      initials: 'MS',
      sector: 'Technology',
      exchange: 'NASDAQ',
      market: 'US Market',
      price: 441.77,
      change: 1.14,
      changePositive: true,
      marketCap: '$3.3T',
      pe: '35.2x',
      peRaw: 35.2,
      revenueGrowth: '16%',
      revenueGrowthRaw: 16,
      grossMargin: '70.1%',
      operatingMargin: '44.6%',
      roe: '38.2%',
      marketStatus: 'open',
      accentColor: '#00a4ef',
      peers: [
        { ticker: 'MSFT', company: 'Microsoft', pe: '35.2x', revenueGrowth: '16%', isSelf: true  },
        { ticker: 'GOOG', company: 'Alphabet',  pe: '23.4x', revenueGrowth: '14%', isSelf: false },
        { ticker: 'AMZN', company: 'Amazon',    pe: '41.2x', revenueGrowth: '11%', isSelf: false },
      ],
      aiInsight: {
        standout: [
          'Azure cloud growing at 29% YoY gaining market share against AWS',
          'Copilot AI integration across Office 365 creating premium enterprise tier',
          '70%+ gross margins reflecting high-value software and cloud mix',
        ],
        watch: [
          'OpenAI partnership cost structure and exclusivity risk as AI ecosystem matures',
          'Azure capacity constraints limiting near-term growth ceiling',
          'Activision Blizzard integration costs weighing on near-term free cash flow',
        ],
        takeaway:
          'Microsoft is executing one of the most credible enterprise AI monetization strategies among mega-cap tech, with Azure and Copilot as the primary growth engines.',
      },
      catalysts: [
        { date: 'Aug 2024', text: 'Azure AI services crossed $10B annualized revenue run rate' },
        { date: 'Jul 2024', text: 'Microsoft 365 Copilot reached 1M paid enterprise seats' },
        { date: 'Jun 2024', text: '$3.3B investment in Wisconsin AI data center infrastructure announced' },
        { date: 'May 2024', text: 'FY Q3 earnings beat with cloud revenue growing 21% YoY' },
      ],
    },
    {
      id: 4,
      ticker: 'META',
      name: 'Meta Platforms Inc.',
      shortName: 'Meta Platforms',
      initials: 'MT',
      sector: 'Technology',
      exchange: 'NASDAQ',
      market: 'US Market',
      price: 512.34,
      change: 2.12,
      changePositive: true,
      marketCap: '$1.3T',
      pe: '26.8x',
      peRaw: 26.8,
      revenueGrowth: '27%',
      revenueGrowthRaw: 27,
      grossMargin: '81.8%',
      operatingMargin: '37.9%',
      roe: '33.7%',
      marketStatus: 'open',
      accentColor: '#0082fb',
      peers: [
        { ticker: 'META', company: 'Meta',      pe: '26.8x', revenueGrowth: '27%', isSelf: true  },
        { ticker: 'SNAP', company: 'Snap',      pe: 'N/M',   revenueGrowth: '19%', isSelf: false },
        { ticker: 'PINS', company: 'Pinterest', pe: '29.1x', revenueGrowth: '23%', isSelf: false },
      ],
      aiInsight: {
        standout: [
          'Ad revenue reaccelerating driven by AI-optimized targeting and Reels monetization',
          'Llama open-source AI strategy building developer ecosystem and talent magnetism',
          '81.8% gross margins among the highest in large-cap internet companies',
        ],
        watch: [
          'Reality Labs losses exceeding $5B annually with uncertain long-term ROI',
          'EU regulatory risk around data privacy and ad targeting practices',
          'Teen engagement trends on Instagram versus TikTok competitive dynamics',
        ],
        takeaway:
          "Meta has successfully pivoted from metaverse skepticism to credible AI advertising leadership, with Llama positioning it as an open-source AI ecosystem player.",
      },
      catalysts: [
        { date: 'Aug 2024', text: 'Q2 2024 revenue grew 22% YoY to $39.1B — beat across all segments' },
        { date: 'Jul 2024', text: 'Llama 3.1 405B released, matching GPT-4 on key reasoning benchmarks' },
        { date: 'Jun 2024', text: 'Meta AI reached 400M monthly active users across all platforms' },
        { date: 'May 2024', text: 'Instagram Reels ad revenue grew 35% contributing to significant beat' },
      ],
    },
    {
      id: 5,
      ticker: 'AMZN',
      name: 'Amazon.com Inc.',
      shortName: 'Amazon.com',
      initials: 'AZ',
      sector: 'E-Commerce',
      exchange: 'NASDAQ',
      market: 'US Market',
      price: 188.40,
      change: 1.58,
      changePositive: true,
      marketCap: '$1.97T',
      pe: '41.2x',
      peRaw: 41.2,
      revenueGrowth: '11%',
      revenueGrowthRaw: 11,
      grossMargin: '48.0%',
      operatingMargin: '9.9%',
      roe: '22.1%',
      marketStatus: 'open',
      accentColor: '#ff9900',
      peers: [
        { ticker: 'AMZN', company: 'Amazon',   pe: '41.2x', revenueGrowth: '11%', isSelf: true  },
        { ticker: 'JD',   company: 'JD.com',   pe: '14.2x', revenueGrowth: '4%',  isSelf: false },
        { ticker: 'SHOP', company: 'Shopify',  pe: '72.1x', revenueGrowth: '25%', isSelf: false },
      ],
      aiInsight: {
        standout: [
          'AWS growing 19% YoY maintaining 31% global cloud infrastructure market share',
          'Advertising segment now $50B+ annual revenue business at very high margins',
          'Operating income margins expanding rapidly after years of infrastructure investment',
        ],
        watch: [
          'E-commerce margin compression from same-day delivery cost buildup',
          'Antitrust investigations into marketplace practices and seller fee structures',
          'AWS competitive pressure as Azure gains enterprise AI workload share',
        ],
        takeaway:
          'Amazon is transitioning from a low-margin retail story to a high-margin cloud and advertising platform, with AWS and Ads now generating the vast majority of operating income.',
      },
      catalysts: [
        { date: 'Aug 2024', text: 'AWS revenue grew 19% to $26.3B in Q2 — growth rate reaccelerating' },
        { date: 'Jul 2024', text: 'Amazon Ads crossed $12.8B quarterly revenue for the first time' },
        { date: 'Jun 2024', text: 'Project Kuiper satellite internet launched first production satellites' },
        { date: 'May 2024', text: 'Prime membership fee increased in multiple international markets' },
      ],
    },
    {
      id: 6,
      ticker: 'TSLA',
      name: 'Tesla Inc.',
      shortName: 'Tesla Inc.',
      initials: 'TS',
      sector: 'Consumer',
      exchange: 'NASDAQ',
      market: 'US Market',
      price: 219.80,
      change: -1.84,
      changePositive: false,
      marketCap: '$699B',
      pe: '58.9x',
      peRaw: 58.9,
      revenueGrowth: '2%',
      revenueGrowthRaw: 2,
      grossMargin: '17.9%',
      operatingMargin: '6.3%',
      roe: '14.2%',
      marketStatus: 'open',
      accentColor: '#e31937',
      peers: [
        { ticker: 'TSLA', company: 'Tesla',   pe: '58.9x', revenueGrowth: '2%',  isSelf: true  },
        { ticker: 'F',    company: 'Ford',    pe: '12.1x', revenueGrowth: '6%',  isSelf: false },
        { ticker: 'GM',   company: 'GM',      pe: '5.8x',  revenueGrowth: '9%',  isSelf: false },
      ],
      aiInsight: {
        standout: [
          'FSD software represents a potentially high-margin future recurring revenue stream',
          'Energy storage business growing 100%+ YoY diversifying beyond automotive',
          'Supercharger network becoming industry standard adopted by Ford and GM',
        ],
        watch: [
          'Auto gross margins compressed to 17.9% from 25%+ highs due to price cuts',
          'EV competition intensifying from BYD in China and legacy OEMs globally',
          'Robotaxi regulatory timeline uncertain with approvals still pending in key states',
        ],
        takeaway:
          'Tesla is increasingly valued as an AI and energy company rather than an automaker, but near-term fundamentals reflect automotive margin pressure and slowing EV demand growth.',
      },
      catalysts: [
        { date: 'Aug 2024', text: 'Robotaxi event scheduled for October 2024 with full autonomous vehicle reveal' },
        { date: 'Jul 2024', text: 'Q2 deliveries at 443,956 vehicles — above 439K consensus estimate' },
        { date: 'Jun 2024', text: 'FSD Version 12.5 released with significant real-world autonomy improvement' },
        { date: 'May 2024', text: 'Megapack energy storage revenue grew 157% YoY to $3.0B quarterly' },
      ],
    },
    {
      id: 7,
      ticker: 'RELIANCE',
      name: 'Reliance Industries Ltd.',
      shortName: 'Reliance Industries',
      initials: 'RL',
      sector: 'Energy',
      exchange: 'NSE',
      market: 'Indian Market',
      price: 2941.50,
      change: 0.72,
      changePositive: true,
      marketCap: '₹19.9T',
      pe: '28.4x',
      peRaw: 28.4,
      revenueGrowth: '9%',
      revenueGrowthRaw: 9,
      grossMargin: '22.1%',
      operatingMargin: '14.3%',
      roe: '11.2%',
      marketStatus: 'closed',
      accentColor: '#1a6b3a',
      peers: [
        { ticker: 'RELIANCE', company: 'Reliance', pe: '28.4x', revenueGrowth: '9%', isSelf: true  },
        { ticker: 'ONGC',     company: 'ONGC',     pe: '8.2x',  revenueGrowth: '4%', isSelf: false },
        { ticker: 'IOC',      company: 'IOC',       pe: '9.1x',  revenueGrowth: '3%', isSelf: false },
      ],
      aiInsight: {
        standout: [
          'Jio Platforms reaching 478M subscribers driving digital India adoption at scale',
          "Retail segment is India's largest with 18,040 stores and growing e-commerce arm",
          'New Energy business targeting $75B investment in green hydrogen and solar by 2030',
        ],
        watch: [
          'O2C segment margins sensitive to global crude oil price volatility',
          'Jio 5G monetization timeline uncertain as ARPU remains low at ~₹182',
          'Retail competition from Amazon India and Flipkart intensifying in e-commerce',
        ],
        takeaway:
          'Reliance is a diversified conglomerate transitioning from energy to digital and retail, with Jio and Reliance Retail increasingly driving the long-term investment thesis.',
      },
      catalysts: [
        { date: 'Aug 2024', text: 'Jio 5G rollout completed across all Indian districts ahead of schedule' },
        { date: 'Jul 2024', text: 'Q1 FY25 consolidated net profit rose 5% YoY to ₹15,138 crore' },
        { date: 'Jun 2024', text: 'Reliance Retail acquired Shein India license for fashion e-commerce relaunch' },
        { date: 'May 2024', text: 'New Energy solar gigafactory in Gujarat commenced commercial production' },
      ],
    },
    {
      id: 8,
      ticker: 'BRK.B',
      name: 'Berkshire Hathaway Inc.',
      shortName: 'Berkshire Hathaway',
      initials: 'BH',
      sector: 'Financials',
      exchange: 'NYSE',
      market: 'US Market',
      price: 368.22,
      change: -0.23,
      changePositive: false,
      marketCap: '$803B',
      pe: '21.4x',
      peRaw: 21.4,
      revenueGrowth: '6%',
      revenueGrowthRaw: 6,
      grossMargin: '31.2%',
      operatingMargin: '11.8%',
      roe: '13.1%',
      marketStatus: 'open',
      accentColor: '#8b6914',
      peers: [
        { ticker: 'BRK.B', company: 'Berkshire', pe: '21.4x', revenueGrowth: '6%', isSelf: true  },
        { ticker: 'JPM',   company: 'JPMorgan',  pe: '12.8x', revenueGrowth: '9%', isSelf: false },
        { ticker: 'BAC',   company: 'BofA',      pe: '13.2x', revenueGrowth: '5%', isSelf: false },
      ],
      aiInsight: {
        standout: [
          '$277B cash position provides unmatched optionality for large-scale acquisitions',
          'GEICO insurance returning to profitability after significant operational restructuring',
          'Railroad and energy businesses generating stable compounding cash flows year after year',
        ],
        watch: [
          'Succession uncertainty as Warren Buffett approaches 94 — market reaction risk',
          'Large Apple stake (~$135B) creates concentrated equity portfolio exposure',
          'Reduced acquisition activity suggests management finds current valuations stretched',
        ],
        takeaway:
          'Berkshire Hathaway represents a defensive value holding with unparalleled financial flexibility, though succession concerns and record cash balances reflect caution on current market valuations.',
      },
      catalysts: [
        { date: 'Aug 2024', text: 'Berkshire reduced Apple stake by 50% — signaling valuation concern' },
        { date: 'Jul 2024', text: 'Operating earnings reached $11.6B in Q2 2024 — a quarterly record' },
        { date: 'Jun 2024', text: 'BNSF Railroad reported improved operating ratio after cost initiatives' },
        { date: 'May 2024', text: 'Annual meeting confirmed Greg Abel as designated successor to Buffett' },
      ],
    },
  ];
  
  export const TOP_GAINERS = [
    { ticker: 'NVDA',  name: 'NVIDIA Corporation',   change: '+4.28%' },
    { ticker: 'META',  name: 'Meta Platforms',        change: '+2.12%' },
    { ticker: 'AMZN',  name: 'Amazon.com Inc.',       change: '+1.58%' },
  ];
  
  export const TOP_LOSERS = [
    { ticker: 'TSLA',  name: 'Tesla Inc.',            change: '-1.84%' },
    { ticker: 'BRK.B', name: 'Berkshire Hathaway',   change: '-0.23%' },
    { ticker: 'XOM',   name: 'Exxon Mobil Corp.',     change: '-0.41%' },
  ];
  
  export const FILTER_CHIPS = [
    'All Stocks',
    'US Market',
    'Indian Market',
    'Technology',
    'AI & Semiconductors',
    'E-Commerce',
    'Financials',
    'Energy',
    'Consumer',
  ];
  
  export const SORT_OPTIONS = [
    { value: 'default',       label: 'Most Viewed'    },
    { value: 'change',        label: 'Daily Change'   },
    { value: 'revenueGrowth', label: 'Revenue Growth' },
    { value: 'pe',            label: 'P/E Ratio'      },
    { value: 'alphabetical',  label: 'Alphabetical'   },
  ];