spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/finlingo

spring.datasource.username=${FINLINGO_DB_USERNAME}
spring.datasource.password=${FINLINGO_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Finnhub API Configuration
finnhub.api.key=${FINNHUB_API_KEY}
finnhub.api.base-url=https://finnhub.io/api/v1

# JWT Security Configuration (Must be at least 256 bits / 32 characters)
jwt.secret=${FINLINGO_JWT_SECRET}
jwt.expiration-ms=604800000
gemini.api.key = ${GEMINI_API_KEY}